config/routes.rb
Rails.application.routes.draw do
  resources :beers, only: %i[index show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'beers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beer.rb
class Beer < PunkApi::Beer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.all(page: params[:page], name: params[:name])
  end

  def show
    @beer = Beer.find(params[:id])
  rescue PunkApi::NotFoundError
    raise ActionController::RoutingError, 'Not Found'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_beer.html.erb
<div class="group relative">
  <div class="rounded-lg bg-zinc-50 group-hover:bg-zinc-100 ">
    <%= render BeerImageComponent.new(beer) %>
  </div>

  <h2 class="mt-4 text-base font-semibold text-gray-900">
    <%= link_to beer, data: {turbo_frame: '_top' } do %>
      <span class="absolute inset-0"></span>
      <%= truncate(beer.name, length: 25) %>
    <% end %>
  </h2>

  <p class="mt-1 text-sm text-gray-500"><%= beer.abv %>% vol</p>
</div>

app/views/beers/index.html.erb
<div class="px-4 py-16 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-baseline sm:justify-between">
    <h1 class="text-2xl font-bold tracking-tight text-gray-900">
      <%= link_to 'Beers', beers_path %>
    </h1>
    
    <%= form_with(url: beers_path, method: :get, data: { controller: "form", turbo_frame: "beers", turbo_action: "replace" }, class: 'w-48') do |form| %>
      <%= form.text_field :name, value: params[:name], type: :search, placeholder: 'Search...', data: { action: "form#submit"}, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-1 focus:ring-inset focus:ring-gray-400 sm:text-sm sm:leading-6' %>
    <% end %>
  </div>

  <%= turbo_frame_tag "beers", data: { turbo_action: "advance" } do %>
    <% if @beers.present? %>
      <div class="mt-6 grid grid-cols-1 gap-y-10 sm:grid-cols-2 md:grid-cols-5 sm:gap-x-6 lg:gap-x-8">
        <%= render @beers.entries %>
      </div>
    
      <%= render PaginationComponent.new(paginator: @beers, url: ->(page) { beers_url(page:, name: params[:name].presence) }) %>
    <% else %>
      <div class="text-center">
        <p class="mt-12 text-sm text-gray-500">Your search "<span class="font-semibold"><%= params[:name] %></span>" gave no <%= 'further ' unless @beers.first_page? %> results</p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/beers/show.html.erb
<div class="sm:pt-16 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-2xl lg:max-w-none lg:grid lg:grid-cols-2 lg:items-start lg:gap-x-8">
    <div class="rounded-lg bg-zinc-100">
      <%= render BeerImageComponent.new(@beer, size: :xl) %>
    </div>

    <div class="mt-10 px-4 sm:px-0 lg:mt-0">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900"><%= @beer.name %></h1>

      <div class="mt-3">
        <p class="text-xl tracking-tight text-gray-900"><%= @beer.abv %>% vol</p>
      </div>

      <div class="mt-4 space-y-6 text-base text-gray-700">
        <p><%= @beer.description %></p>
      </div>

      <div class="mt-6 border-t">
        <h3 class="text-gray-900 text-sm font-medium pt-6 pb-2">Suitable dishes</h3>

        <div class="prose prose-sm pb-6">
          <ul>
            <% @beer.food_pairing.each do |food| %>
              <li><%= food %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mx-auto max-w-7xl">
      <%= yield %>
    </main>
  </body>
</html>